name             'ECHOcommunity-cookbook'
maintainer       'Nate Flood'
maintainer_email 'nflood@echonet.org'
license          'You Seriously Will Not Use This'
description      'Installs/Configures ECHOcommunity-cookbook'
long_description 'Custom Chef Cookbook For ECHOcommunity AWS OPSworks Instances'
version          '0.1.0'
